### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by shammishailaj** [willscott/go-nfs#9]
Hi

I am getting:

```
go: github.com/willscott/go-nfs@v0.0.0-20201019040824-49fd33e9cb45 requires
	github.com/willscott/memphis@v0.0.0-20200912205913-768fef98189f requires
	go.polydawn.net/go-timeless-api@v0.0.0-00010101000000-000000000000: unrecognized import path "go.polydawn.net/go-timeless-api": https fetch: Get "https://go.polydawn.net/go-timeless-api?go-get=1": dial tcp 107.170.61.58:443: connect: connection refused
```
Probably `go.polydawn.net/*`  needs to be replaced with `github.com/polydawn/*`

**Comment by willscott** [comment]
ugh. I probably need the same replace directives in the go.mod of this repo as are in [memphis](https://github.com/willscott/memphis/blob/master/go.mod#L14)

Sadly, the import for timeless can't be set to github because `go-timeless-api` gets referenced through imports on the [polydawn](https://github.com/polydawn/rio/blob/master/fs/metadata.go#L6) domain throughout.

**Comment by willscott** [comment]
cc @warpfork - i think the issue is everyone including this library now would also need to put in the replace lines to resolve timeless. I may make a downstream `go.mod` wrapped version of rio for these so that other projects can make use of it within the now-dominant go.mod ecosystem.

**Comment by willscott** [comment]
Okay. https://github.com/polydawn/rio/pull/11 should provide a commit to pin in memphis that will allow removal of the replace directives and mitigate this issue.
